---

- name: Cleanup data on Netbox
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - include_vars: main.yml

    - name: Cleanup data on Netbox
      block:
      - name: Cleanup device type data on Netbox
        netbox.netbox.netbox_device_type:
          netbox_url: "{{ net_netbox_url }}"
          netbox_token: "{{ net_netbox_token }}"
          validate_certs: no
          state: absent
        throttle: 1

      - name: Cleanup devices data on Netbox
        netbox.netbox.netbox_device:
          netbox_url: "{{ net_netbox_url }}"
          netbox_token: "{{ net_netbox_token }}"
          validate_certs: no
          state: absent

      - name: Cleanup interfaces data on Netbox
        netbox.netbox.netbox_device_interface:
          netbox_url: "{{ net_netbox_url }}"
          netbox_token: "{{ net_netbox_token }}"
          validate_certs: no

      - name: Cleanup IPv4 addresses data on Netbox
        netbox.netbox.netbox_ip_address:
          netbox_url: "{{ net_netbox_url }}"
          netbox_token: "{{ net_netbox_token }}"
          validate_certs: no
          state: absent

      - name: Cleanup VLAN data on Netbox
        netbox.netbox.netbox_vlan:
          netbox_url: "{{ net_netbox_url }}"
          netbox_token: "{{ net_netbox_token }}"
          validate_certs: no
          state: absent
