---

- name: Cleanup data on Netbox
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - include_vars: main.yml

    # - name: Debug VLANs on Netbox
    #   debug:
    #     var: item
    #   loop: "{{ query('netbox.netbox.nb_lookup', 'vlans',
    #                 api_endpoint=net_netbox_url,
    #                 token=net_netbox_token,
    #                 validate_certs=False) }}"
    #   when: inventory_hostname == switch_vlans

    # - name: Cleanup VLAN data on Netbox
    #   netbox.netbox.netbox_vlan:
    #     netbox_url: "{{ net_netbox_url }}"
    #     netbox_token: "{{ net_netbox_token }}"
    #     validate_certs: no
    #     data:
    #       site: "{{ item.value.site.name }}"
    #       name: "{{ item.value.name }}"
    #       vid: "{{ item.value.vid }}"          
    #     state: absent
    #   loop: "{{ query('netbox.netbox.nb_lookup', 'vlans',
    #                 api_endpoint=net_netbox_url,
    #                 token=net_netbox_token,
    #                 validate_certs=False) }}"
    #   when: inventory_hostname == switch_vlans

    # - name: Debug IPv4 addresses data on Netbox
    #   debug:
    #     var: item
    #   loop: "{{ query('netbox.netbox.nb_lookup', 'ip-addresses',
    #                 api_endpoint=net_netbox_url,
    #                 token=net_netbox_token,
    #                 validate_certs=False) }}"

    # - name: Cleanup IPv4 addresses data on Netbox
    #   netbox.netbox.netbox_ip_address:
    #     netbox_url: "{{ net_netbox_url }}"
    #     netbox_token: "{{ net_netbox_token }}"
    #     validate_certs: no
    #     data: 
    #       assigned_object:
    #         device: "{{ item.value.assigned_object.device.name }}"
    #         name: "{{ item.value.assigned_object.name }}"
    #       family: "{{ item.value.family.value }}"
    #       address: "{{ item.value.address }}"
    #     state: absent
    #   loop: "{{ query('netbox.netbox.nb_lookup', 'ip-addresses',
    #                 api_endpoint=net_netbox_url,
    #                 token=net_netbox_token,
    #                 validate_certs=False) }}"

    # - name: Debug interfaces data on Netbox
    #   debug:
    #     var: item
    #   loop: "{{ query('netbox.netbox.nb_lookup', 'interfaces',
    #                 api_endpoint=net_netbox_url,
    #                 token=net_netbox_token,
    #                 validate_certs=False) }}"

    # - name: Cleanup interfaces data on Netbox
    #   netbox.netbox.netbox_device_interface:
    #     netbox_url: "{{ net_netbox_url }}"
    #     netbox_token: "{{ net_netbox_token }}"
    #     validate_certs: no
    #     data: 
    #       device: "{{ item.value.device.name }}"
    #       name: "{{ item.value.name }}"
    #       type: "{{ item.value.type.label }}"
    #       description: "{{ item.value.name }}"
    #     state: absent
    #   loop: "{{ query('netbox.netbox.nb_lookup', 'interfaces',
    #                 api_endpoint=net_netbox_url,
    #                 token=net_netbox_token,
    #                 validate_certs=False) }}"

    # - name: Debug devices data on Netbox
    #   debug:
    #     var: item
    #   loop: "{{ query('netbox.netbox.nb_lookup', 'devices',
    #                 api_endpoint=net_netbox_url,
    #                 token=net_netbox_token,
    #                 validate_certs=False) }}"

    # - name: Cleanup devices data to Netbox
    #   netbox.netbox.netbox_device:
    #     netbox_url: "{{ net_netbox_url }}"
    #     netbox_token: "{{ net_netbox_token }}"
    #     validate_certs: no
    #     data: 
    #       name: "{{ item.value.name }}"
    #       site: "{{ site }}"
    #       serial: "{{ item.value.serial }}"
    #       device_type: "{{ item.value.device_type }}"
    #       device_role: "{{ item.value.device_role }}"
    #       comments: "Added by AAP"
    #     state: absent
    #   loop: "{{ query('netbox.netbox.nb_lookup', 'devices',
    #           api_endpoint=net_netbox_url,
    #           token=net_netbox_token,
    #           validate_certs=False) }}"

    # - name: Debug device types data on Netbox
    #   debug:
    #     var: item
    #   loop: "{{ query('netbox.netbox.nb_lookup', 'device-types',
    #                 api_endpoint=net_netbox_url,
    #                 token=net_netbox_token,
    #                 validate_certs=False) }}"

    # - name: Push device type data to Netbox
    #   netbox.netbox.netbox_device_type:
    #     netbox_url: "{{ net_netbox_url }}"
    #     netbox_token: "{{ net_netbox_token }}"
    #     validate_certs: no
    #     data: 
    #       model: "{{ item.value.model }}"
    #       manufacturer: "{{ item.value.manufacturer }}"
    #       slug: "{{ item.value.slug }}"
    #     state: absent
    #   loop: "{{ query('netbox.netbox.nb_lookup', 'device-types',
    #                 api_endpoint=net_netbox_url,
    #                 token=net_netbox_token,
    #                 validate_certs=False) }}"

    - name: Debug site data on Netbox
      debug:
        var: item
      loop: "{{ query('netbox.netbox.nb_lookup', 'sites',
                    api_endpoint=net_netbox_url,
                    token=net_netbox_token,
                    validate_certs=False) }}"

                    