---

- name: Cleanup data on Netbox
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - include_vars: main.yml

    - name: Debug VLANs on Netbox
      debug:
        var: item
      loop: "{{ query('netbox.netbox.nb_lookup', 'vlans',
                    api_endpoint=net_netbox_url,
                    token=net_netbox_token,
                    validate_certs=False) }}"
      when: inventory_hostname == switch_vlans

    - name: Cleanup VLAN data on Netbox
      netbox.netbox.netbox_vlan:
        netbox_url: "{{ net_netbox_url }}"
        netbox_token: "{{ net_netbox_token }}"
        validate_certs: no
        data:
          site: "{{ item.value.site.name }}"
          name: "{{ item.value.name }}"
          vid: "{{ item.value.vid }}"          
        state: absent
      loop: "{{ query('netbox.netbox.nb_lookup', 'vlans',
                    api_endpoint=net_netbox_url,
                    token=net_netbox_token,
                    validate_certs=False) }}"
      when: inventory_hostname == switch_vlans

    - name: Debug IPv4 addresses data on Netbox
      debug:
        var: item
      loop: "{{ query('netbox.netbox.nb_lookup', 'ip-addresses',
                    api_endpoint=net_netbox_url,
                    token=net_netbox_token,
                    validate_certs=False) }}"

    - name: Cleanup IPv4 addresses data on Netbox
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ net_netbox_url }}"
        netbox_token: "{{ net_netbox_token }}"
        validate_certs: no
        data: 
          assigned_object:
            device: "{{ item.value.assigned_object.device.name }}"
            name: "{{ item.value.assigned_object.name }}"
          family: "{{ item.value.family.value }}"
          address: "{{ item.value.address }}"
        state: absent
      loop: "{{ query('netbox.netbox.nb_lookup', 'ip-addresses',
                    api_endpoint=net_netbox_url,
                    token=net_netbox_token,
                    validate_certs=False) }}"




    - name: Cleanup device type data on Netbox
      netbox.netbox.netbox_device_type:
        netbox_url: "{{ net_netbox_url }}"
        netbox_token: "{{ net_netbox_token }}"
        validate_certs: no
        state: absent
      throttle: 1

    - name: Cleanup devices data on Netbox
      netbox.netbox.netbox_device:
        netbox_url: "{{ net_netbox_url }}"
        netbox_token: "{{ net_netbox_token }}"
        validate_certs: no
        state: absent

    - name: Cleanup interfaces data on Netbox
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ net_netbox_url }}"
        netbox_token: "{{ net_netbox_token }}"
        validate_certs: no


