---

- name: Collect Cisco IOS, NXOS and Arista EOS Facts
  hosts: all
  gather_facts: false
  tasks:
    - include_vars: main.yml

    - name: IOS gatthering facts
      block:
      - name: IOS facts
        connection: local
        cisco.ios.ios_facts:
          gather_subset:
            - hardware
          gather_network_resources:
            - "interfaces"
            - "l2_interfaces"
            - "l3_interfaces"
            - "acl_interfaces"
            - "static_routes" 
            - "acls" 
            - "vlans"
        register: _ios_facts
        become: true
      - name: Debug IOS facts
        debug:
          var: _ios_facts
      - name: Set IOS facts
        set_fact:
          _facts: "{{ _ios_facts }}"
      when: ansible_network_os == 'ios'

    - name: NXOS gatthering facts
      block:
      - name: NXOS facts
        connection: local
        cisco.nxos.nxos_facts:
          gather_subset:
            - hardware
          gather_network_resources:
            - "interfaces"
            - "l2_interfaces"
            - "l3_interfaces"
            - "acl_interfaces"
            - "static_routes" 
            - "acls" 
        register: _nxos_facts
        become: true
      - name: Debug NXOS facts
        debug:
          var: _nxos_facts
      - name: Set NXOS facts
        set_fact:
          _facts: "{{ _nxos_facts }}"
      when: ansible_network_os == 'nxos'

    - name: EOS gatthering facts
      block:
      - name: EOS facts
        connection: local
        arista.eos.eos_facts:
          gather_subset:
            - hardware
          gather_network_resources:
            - all
        register: _eos_facts
        become: true
      - name: Debug EOS facts
        debug:
          var: _eos_facts
      - name: Set EOS facts
        set_fact:
          _facts: "{{ _eos_facts }}"
      when: ansible_network_os == 'eos'

    - name: Store facts to a variable
      set_stats:
        data:
          #_facts_{{ inventory_hostname | regex_replace('-') }}: "{{ _facts }}"
          _facts: "{{ _facts }}"
        per_host: yes

    - name: Store facts to a variable 2
      set_stats:
        data:
          _facts_{{ inventory_hostname | regex_replace('-') }}: "{{ _facts }}"
          #_facts: "{{ _facts }}"
        #per_host: yes