---

# On Ansible:
# On the Template, set Variables "Prompt on launch" checkbox 
# Example: https://medium.com/@stephenpaynter/netbox-webhooks-with-ansible-tower-eaa6dd98320



# On Netbox
# User icon -> Admin -> Webhooks -> Add (DCIM->Interface, Enabled)




- name: Update interface vlan configs, triggered by Netbox changes
  hosts: localhost
  gather_facts: false
  tasks:
    - include_vars: main.yml

    - debug:
        msg: "{{ interface_name }}, {{ interface_id }}, {{ event }}, {{ timestamp }}, {{ data }}, {{ limit }}" 



    # - name: Push interfaces data to Netbox
    #   netbox.netbox.netbox_device_interface:
    #     netbox_url: "{{ net_netbox_url }}"
    #     netbox_token: "{{ net_netbox_token }}"
    #     validate_certs: no
    #     data: 
    #       device: "{{ inventory_hostname }}"
    #       name: "{{ item.name }}"
    #       type: "Virtual"
    #       description: "{{ item.name }} description"
    #     state: present
    #   loop: "{{ _facts.ansible_facts.ansible_network_resources.interfaces }}"
    #   throttle: 1