---

- name: Update interface vlan configs, triggered by Netbox changes
  hosts: "{{ device }}"
  gather_facts: false


  tasks:
    - include_vars: main.yml

    - name: Debug Interface ID
      debug:
        msg: "Updating interface ID : {{ interface_id }}  " 


    - name: Get interface parameters
      set_fact:
        netbox_interface:  "{{ query('netbox.netbox.nb_lookup', 'interfaces', api_filter='id=' ~ interface_id,
                      api_endpoint='http://192.168.1.200/',
                      token='db59d5f08ff66721c64bd181e2b23da2e48d2d87', validate_certs=false) }}"
                      
    - name: Display interface parameters
      debug:
        msg: "{{ netbox_interface }}"

   

    - name: Merge Interfaces provided configuration with device configuration
      arista.eos.eos_interfaces:
        config:
        - name: "{{ netbox_interface[0].name }}"
          description: Configured and Merged by Ansible Network
          enabled: "{{ netbox_interface[0].enabled }}"
          mtu: "{{ netbox_interface[0].mtu }}"
          enabled: true


    - name: Merge Vlans provided configuration with device configuration.
      arista.eos.eos_l2_interfaces:
        config:
        - name: "{{ netbox_interface[0].name }}"
          mode: "{{ netbox_interface[0].mode.value }}"
          access:
            vlan: "{{ netbox_interface[0].untagged_vlan.vid }}"
        state: replaced
      when:  (netbox_interface[0].untagged_vlan is defined) and (netbox_interface[0].untagged_vlan is not none)