---

- name: Update interface vlan configs, triggered by Netbox changes
  hosts: localhost
  gather_facts: false


  tasks:
    - include_vars: main.yml

    - name: Debug Netbox data structure
      debug:
        msg: "{{ interface_id }}" 


    - name: set fact
      set_fact:
        netbox_interface:  "{{ query('netbox.netbox.nb_lookup', 'api_filter='id={{ interface_id }}',
                      api_endpoint='http://192.168.1.200/',
                      token='db59d5f08ff66721c64bd181e2b23da2e48d2d87', validate_certs=false) }}"
    - name: debug
      debug:
        msg: "{{ netbox_interface }}"


    - name: Merge provided configuration with device configuration
      cisco.ios.ios_interfaces:
        config:
        - name: "{{ data['name'] }}"
          description: Configured and Merged by Ansible Network
          mtu: 2800
          enabled: "{{ netbox_interface.enabled }}"
          speed: 100
          duplex: full
          enabled: true


    - name: Cisco IOS update IPv4 to l3 interface on {{ device }}
      cisco.ios.ios_l3_interfaces:
        config: 
          - name: "{{ interface }}"
            ipv4:
            - address: "{{ ip_address }}"
        state: merged
      become: true
      when: address_family == '4'

    - name: Cisco IOS update IPv6 to l3 interface on {{ device }}
      cisco.ios.ios_l3_interfaces:
        config: 
          - name: "{{ interface }}"
            ipv6:
            - address: "{{ ip_address }}"
        state: merged
      become: true
      when: address_family == '6'

    - name: Cisco IOS update description to interface on {{ device }}
      cisco.ios.ios_interfaces:
        config:
        - name: "{{ interface }}"
          description: "{{ description }}"
      become: true
