---

- name: Update interface vlan configs, triggered by Netbox changes
  hosts: "{{ device }}" 
  gather_facts: false

  vars:
    input:  "{{ data | replace(\"'\", '\"') }}  " 

  tasks:
    - include_vars: main.yml

    - name: Debug Netbox data structure
      debug:
        msg: "{{ data }}" 


    - name: Debug Netbox data structure JSON
      debug:
        msg: "{{ data | replace(\"'\", '\"') }} | to_json  " 

    - name: Debug Netbox data structure JSON
      debug:
        msg: "{{ data | replace(\"'\", '\"') }} | to_json | from_json " 



    - name: Merge provided configuration with device configuration
      cisco.ios.ios_interfaces:
        config:
        - name: "{{ data['name'] }}"
          description: Configured and Merged by Ansible Network
          mtu: 2800
          enabled: false
          speed: 100
          duplex: full
          enabled: true


    - name: Cisco IOS update IPv4 to l3 interface on {{ device }}
      cisco.ios.ios_l3_interfaces:
        config: 
          - name: "{{ interface }}"
            ipv4:
            - address: "{{ ip_address }}"
        state: merged
      become: true
      when: address_family == '4'

    - name: Cisco IOS update IPv6 to l3 interface on {{ device }}
      cisco.ios.ios_l3_interfaces:
        config: 
          - name: "{{ interface }}"
            ipv6:
            - address: "{{ ip_address }}"
        state: merged
      become: true
      when: address_family == '6'

    - name: Cisco IOS update description to interface on {{ device }}
      cisco.ios.ios_interfaces:
        config:
        - name: "{{ interface }}"
          description: "{{ description }}"
      become: true
