---

- name: Update interface vlan configs, triggered by Netbox changes
  hosts: localhost
  gather_facts: false
  tasks:
    - include_vars: main.yml

    - debug:
        msg: "{{ data }}" 

    - debug:
        msg: "{{ device }}, {{ interface }}, {{ vlan_id }}, {{ vlan_name }}, {{ event }}, {{ timestamp }}" 




    # - name: Push interfaces data to Netbox
    #   netbox.netbox.netbox_device_interface:
    #     netbox_url: "{{ net_netbox_url }}"
    #     netbox_token: "{{ net_netbox_token }}"
    #     validate_certs: no
    #     data: 
    #       device: "{{ inventory_hostname }}"
    #       name: "{{ item.name }}"
    #       type: "Virtual"
    #       description: "{{ item.name }} description"
    #     state: present
    #   loop: "{{ _facts.ansible_facts.ansible_network_resources.interfaces }}"
    #   throttle: 1