---

- name: Update interface vlan configs, triggered by Netbox changes
  hosts: "{{ device }}"
  gather_facts: false
  tasks:
    - include_vars: main.yml

    - name: Debug Netbox data structure
      debug:
        msg: "{{ data }}" 

    - name: Debug Netbox relevant variables
      debug:
        msg: "{{ device }}, {{ interface }}, {{ ip_address }}, {{ address_family }}, {{ description }}, {{ event }}, {{ timestamp }}, {{ data }}" 

    # - name: Cisco IOS Add VLAN to l2 interface on {{ device }}
    #   cisco.ios.ios_l2_interfaces:
    #     config:
    #       - name: "{{ interface }}"
    #         mode: access
    #         access:
    #           vlan: "{{ vlan_id }}"
    #     state: merged
    #   become: true

