---

- name: Create site within NetBox with only required information
  netbox_site:
    netbox_url: "{{ net_netbox_url }}"
    netbox_token: "{{ net_netbox_token }}"
    data:
      name: "{{ net_site }}"
    state: present
  delegate_to: localhost
  
- name: Parse facts 
  include_tasks: "parse_facts_{{ ansible_network_os }}.yml"

- name: Parse Interfaces 
  include_tasks: "parse_intf_{{ ansible_network_os }}.yml"

- name: Parse Vlans 
  include_tasks: "parse_vlans_{{ ansible_network_os }}.yml"
