---

- name: JUNOS block
  block:
  - name: JUNOS facts
    junipernetworks.junos.junos_facts:
      gather_subset:
        - hardware
      gather_network_resources:
        - "interfaces"
        - "l2_interfaces"
        - "l3_interfaces"
        - "acl_interfaces"
        - "static_routes" 
        - "acls" 
    register: _junos_facts
    become: true    
  - debug:
      var: _junos_facts
  - set_fact:
      _facts: "{{ _junos_facts }}"

- name: NETBOX block
  block:
  - name: make sure device type is configured
    netbox.netbox.netbox_device_type:
      netbox_url: "{{ net_netbox_url }}"
      netbox_token: "{{ net_netbox_token }}"
      validate_certs: no
      data: 
        model: "{{ _facts.ansible_facts.ansible_net_system | default('unknown') }}"
        manufacturer: "juniper"
        slug: "{{ _facts.ansible_facts.ansible_net_system | default('unknown') }}"
    throttle: 1
    delegate_to: localhost

  - name: Create site within NetBox with only required information
    netbox.netbox.netbox_site:
      netbox_url: "{{ net_netbox_url }}"
      netbox_token: "{{ net_netbox_token }}"
      validate_certs: no
      data:
        name: "{{ net_site }}"
      state: present
    delegate_to: localhost


  - name: push device inventory data to netbox
    netbox.netbox.netbox_device:
      netbox_url: "{{ net_netbox_url }}"
      netbox_token: "{{ net_netbox_token }}"
      validate_certs: no
      data:
        name: "{{ inventory_hostname }}"
        site: "{{ net_site }}"
        serial: "{{ _facts.ansible_facts.ansible_net_serialnum | default(omit) }}"
        device_type: "{{ _facts.ansible_facts.ansible_net_system | default('unknown') }}"
        device_role: "{{ net_device_role }}"
        local_context_data: "{{ _facts.ansible_facts.ansible_network_resources }}"
        custom_fields: 
          device_model: "{{ _facts.ansible_facts.ansible_net_model | default('unknown') }}"
          device_version: "{{ _facts.ansible_facts.ansible_net_version | default('unknown') }}"
        comments: "added by Ansible"
    delegate_to: localhost
  tags: netbox



