---

- name: PARSE VLAN INFORMATIONS
  block:
  - name: gather facts for L2 interface information
    arista.eos.eos_facts:
      gather_network_resources: 
        - "l2_interfaces"
        - vlans
      gather_subset:
        - min
    register: _intf_result
    become: true
  - debug: 
      var: _intf_result
      verbosity: 2
  tags: [parse_vlan]

- name: NETBOX BLOCK
  block:
  - name: push VLAN database to netbox
    netbox.netbox.netbox_vlan:
      netbox_url: "{{ net_netbox_url }}"
      netbox_token: "{{ net_netbox_token }}"
      validate_certs: no
      data:
        name: "{{ item.name }}"
        vid: "{{ item.vlan_id }}"
        site: "{{ net_site }}"
    loop: "{{ _intf_result.ansible_facts.ansible_network_resources.vlans }}"

  - name: push intf access VLAN to netbox
    netbox.netbox.netbox_device_interface:
      netbox_url: "{{ net_netbox_url }}"
      netbox_token: "{{ net_netbox_token }}"
      validate_certs: no
      data:
        device: "{{ inventory_hostname }}"
        name: "{{ item.name }}"
        mode: "access"
        untagged_vlan: "{{ item.access.vlan | default(omit) }}"
    loop: "{{ _intf_result.ansible_facts.ansible_network_resources.l2_interfaces }}"
    loop_control:
      label: "{{ item.name }}"
    when: item.access is defined
  tags: [netbox]