---

- include_tasks: parse_facts.yml
  tags: [facts, inventory]

- include_tasks: parse_intf.yml
  tags: [parse_intf]

- include_tasks: parse_vlan.yml
  tags: [parse_vlan] 
  when: inventory_hostname in groups['switch']

