---

- name: JUNOS block
  block:
  - name: JUNOS facts
    junipernetworks.junos.junos_facts:
      gather_subset:
        - hardware
      gather_network_resources:
        - all
    register: _junos_facts
  - debug:
      var: _junos_facts
      verbosity: 2
  - set_fact:
      _facts: "{{ _junos_facts }}"

- name: NETBOX block
  block:


  - name: push device inventory data to netbox
    netbox.netbox.netbox_device:
      netbox_url: "{{ net_netbox_url }}"
      netbox_token: "{{ net_netbox_token }}"
      validate_certs: no
      data:
        name: "rtr4"
        site: "paris"
        serial: "xxxxx"
        device_type: "junos"
        device_role: "router}"
        comments: "added by Ansible"



  - name: push device inventory data to netbox
    netbox.netbox.netbox_device:
      netbox_url: "{{ net_netbox_url }}"
      netbox_token: "{{ net_netbox_token }}"
      validate_certs: no
      data:
        name: "{{ inventory_hostname }}"
        site: "{{ net_site }}"
        serial: "{{ _facts.ansible_facts.ansible_net_serialnum | default(omit) }}"
        device_type: "{{ _facts.ansible_facts.ansible_net_system | default('unknown') }}"
        device_role: "{{ net_device_role }}"
        local_context_data: "{{ _facts.ansible_facts.ansible_network_resources }}"
        custom_fields: 
          device_model: "{{ _facts.ansible_facts.ansible_net_model | default('unknown') }}"
          device_version: "{{ _facts.ansible_facts.ansible_net_version | default('unknown') }}"
        comments: "added by Ansible"
  tags: netbox



